name: Update meeting minutes site

on:
  push:
    branches: ["*"] 
  pull_request:
    branches: ["*"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run script to update index.html
        run: python Documentation/generate_html.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-update index.html file list"
            git push
          fi
